### ISSUE TITLE
Does not support <(cat file1 file2)

### ISSUE THREAD

**Issue by MadBomber** [charmbracelet/mods#178]
`cat file1 file1 | mods "prompt"`. works just fine; however to keep the pipe steam available for other context I use this syntax in bash: `mods "prompt" <(cat file1 file2)` which fails.  Here is an example response that I get which indicates to me that mods is not processing the file descriptor.

```
$ mods "describe the purpose of these two Ruby classes" <(cat cli.rb config.rb)

  It seems there might be a bit of confusion in the question. In the context
  of Ruby programming,  /dev/fd/63  doesn't refer to Ruby classes. Rather, it
  looks like you are referring to a special file in a Unix-like operating
  system.
```

**Comment by caarlos0** [comment]
that's to be expected from bash... `<(command)` creates a temporary file and pass its filename (usually in `/dev/fd/` as you experienced) as an argument, not as stdin.

to achieve what you want, you'll need to do something like:

```bash
mods "describe the purpose of these two Ruby classes" < <(cat cli.rb config.rb)
```

So it redirects the actual contents of the temporary file to STDIN instead of just its filename.


Home this helps 🙏
